### ISSUE TITLE
Error with webdriver

### ISSUE THREAD

**Issue by HFsi** [eth0izzle/Needl#18]
I folowed al the steps, but I get this when executing:

(ERROR) [__init__->_run_job]: Task failed: Traceback (most recent call last):
  File "/opt/needl/needl/schedule/__init__.py", line 84, in _run_job
    ret = job.run()
  File "/opt/needl/needl/schedule/__init__.py", line 336, in run
    ret = self.job_func()
  File "/opt/needl/needl/tasks/google.py", line 17, in search
    browser = utils.get_browser()
  File "/opt/needl/needl/utils.py", line 60, in get_browser
    return webdriver.Chrome(executable_path=chromedriver, chrome_options=chrome_options)
  File "/home/hernan/.local/lib/python3.5/site-packages/selenium/webdriver/chrome/webdriver.py", line 62, in __init__
    self.service.start()
  File "/home/hernan/.local/lib/python3.5/site-packages/selenium/webdriver/common/service.py", line 96, in start
    self.assert_process_still_running()
  File "/home/hernan/.local/lib/python3.5/site-packages/selenium/webdriver/common/service.py", line 109, in assert_process_still_running
    % (self.path, return_code)
selenium.common.exceptions.WebDriverException: Message: Service /opt/needl/data/chromedriver unexpectedly exited. Status code was: 127

Is there anything else that I should do to the driver?
Thanks!

**Comment by eth0izzle** [comment]
@HFsi what system are you on? If you execute chromedriver from your terminal do you get something like:

    Starting ChromeDriver 2.33.506106 (8a06c39c4582fbfbab6966dbb1c38a9173bfb1a2) on port 9515
    Only local connections are allowed.

**Comment by HFsi** [comment]
I´m running Ubuntu Server 17.10.
I tried start, ./, chromedriver...but can´t getting to work....Which is the command to execute it?
Sorry, I´ve very basic understanding o Linux commands...
Thanks

**Comment by eth0izzle** [comment]
It sounds like you have the wrong version of chromedriver. Download for your system and architecture and try again.
